# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Olly Britton
description: > # this means to ignore newlines until "baseurl:"
  My personal site, where I sometimes post stuff.
repository: https://github.com/ollybritton
baseurl: # the subpath of your site, e.g. /blog
url: https://ollybritton.com  # the base hostname & protocol for your site
admin: Olly

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Olly Britton
email: ollybritton@gmail.com

navigation:
  - text: Home
    url: /

  - text: Posts
    url: /posts

  - text: Projects
    url: /projects

  - text: Contact
    url: /contact

projects:
  - name: function-mirror
    description: A project I made at Hacksoton 2017 that takes live webcam and applies a function to every rgb value.
    link: https://ollybritton.github.io/Function-Mirror/
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/function-mirror.png
  - name: boi-lang
    description: A (WIP) implementation of <code>brainf***</code> that replaces the normal symbols with variations on the word "boi".
    link: https://github.com/ollybritton/BoiLang
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/boi-lang.png
  - name: genetic-tea
    description: Uses darwinian evolution to get closer and closer to a the best cup of tea possible.
    link: https://github.com/ollybritton/GeneticTea
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/genetic-tea.png
  - name: number-theory
    description: Number theory and other areas of mathematics which I've made functions for.
    link: https://github.com/ollybritton/Number-Theory
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/number-theory.png
  - name: jacob
    description: A truly useless thing that generates a random Jacob Sartorius vine.
    link: https://github.com/ollybritton/Jacob
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/jacob.png
  - name: store-destruct
    description: Click a button and you can pretend that a department store computer is about to blow up.
    link: https://github.com/ollybritton/storeDestruct
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/store-destruct.png
  - name: punk
    link: punk
    description: Lets you mess with the "Harder, Better, Faster, Stronger" samples.
    image: https://raw.githubusercontent.com/ollybritton/Assets/master/favicon.png

social:
  - service: github
    username: ollybritton
    link: https://github.com/ollybritton

  - service: twitter
    username: olllybr
    link: https://twitter.com/olllybr

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-gist
